
---

apiVersion: v1
kind: Namespace
metadata:
  name: test
  annotations:
    git_commit: deadbeefdeadbeef
    git_project: git@github.com:my-org/rspec_tests.git
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: test-nginx
  annotations:
    git_commit: deadbeefdeadbeef
    git_project: git@github.com:my-org/rspec_tests.git
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: web
          containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: test-nginx
  labels:
    app: test-nginx
  annotations:
    git_commit: deadbeefdeadbeef
    git_project: git@github.com:my-org/rspec_tests.git
spec:
  ports:
  - port: 80
    targetPort: web
    protocol: TCP
  selector:
    app: test-nginx
