name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Check out source code
        uses: actions/checkout@v1
      - name: generate lib/kube_deploy_tools/version.rb for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export VERSION=${GITHUB_REF##*/v}
          cat >lib/kube_deploy_tools/version.rb <<EOF
          module KubeDeployTools
            VERSION = '${VERSION}'
          end
          EOF
      - name: run unit tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake test
      - name: build gem
        run: bundle exec rake build
      - name: build docker image
        run: docker build -t local-registry/kube_deploy_tools .
      ### BELOW: ONLY RUN WHEN MASTER IS PUSHED ###
      - name: push kube_deploy_tools:latest
        if: github.branch == 'refs/heads/master'
        run: bundle exec kdt push --tag=latest kube_deploy_tools
      - uses: toolmantim/release-drafter@v5.2.0
        if: github.branch == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ### BELOW: ONLY RUN WHEN A TAG IS PUSHED ###
      - name: push tagged docker container images to gcr
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(mktemp)
          trap "rm -f ${GOOGLE_APPLICATION_CREDENTIALS}" EXIT
          echo -n "${GOOGLE_APPLICATION_CREDENTIALS_TEXT}" >"$GOOGLE_APPLICATION_CREDENTIALS"

          VERSION=${GITHUB_REF##*/v}
          VERSION_X=${VERSION%%.*}
          gcloud auth configure-docker
          bundle exec kdt push --tag="$VERSION" kube_deploy_tools
          bundle exec kdt push --tag="$VERSION_X" kube_deploy_tools
        env:
          # keyfile for svc-jenkins service account
          GOOGLE_APPLICATION_CREDENTIALS_TEXT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_TEXT }}
      - name: push tagged gem to github packages
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export VERSION=${GITHUB_REF##*/v}
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials
          gem push --key github --host https://rubygems.pkg.github.com/LiveRamp kube_deploy_tools-${VERSION}.gem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
